[package]
name = "margo-sys"
version = "0.1.0"
edition = "2021"
links = "margo"
build = "build.rs"

[lib]
doctest = false

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.63.0"
pkg-config = "0.3"
